### PR TITLE
Build and Deploy a Spring Boot Application using GitHub Actions

### PR DESCRIPTION
**Pull request by karthirm**
## Purpose

* This PR contain all the steps to create a spring boot application with a REST end point and deploy it in Azure using App Service and Github Actions

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[x] Other... Please describe:
```
A documentation kind of PR which describes all the steps involved in deploying a simple Spring Boot Application
## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
mvn clean install
```

* Test the code

```
Deploy the code and hit the endpoint which is present in the newly created Azure App Service.
To test it locally, hit the endpoint present in the ProductController class - http://localhost:8080/message
```

## What to Check
Verify that the following are valid
* Check the endpoint in the Controller class. 
* Deploy the application in Azure and see if it works after appending the endpoint ("/message") at the end of the URL. 

## Other Information

* This is a simple Spring Boot Application with just one REST endpoint

### CODE REVIEW

**Comment by karthirm** [comment]
@microsoft-github-policy-service agree

**Comment by mnriem** [comment]
@karthirm Thank you for your contribution. This repository has a certain structure to it, and we will evaluate to see if we can get your contribution in the same format.

**Comment by karthirm** [comment]
@mnriem -  I have changed all the images to be relative, please check and approve.

**Comment by karthirm** [comment]
@mnriem  - I have also contributed to Azure Spring Cloud Config Server, please check that commit as well.

**Pull request merged**
